import HR.*;

import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        int salaryOperator = 10000;
        int salaryManager = 30000;
        int salaryTopManager = 100000;
        int incomeCompany = 10000000;
        Company company = new Company();
        HireEmployees hire = new HireEmployees();
        company.setIncome(incomeCompany);
        ArrayList <Employee> listHireAll = new ArrayList(){{
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new Manager(salaryManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new TopManager(salaryTopManager, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
            add(new Operator(salaryOperator, company));
        }};
        hire.hireAll(listHireAll);
        company.fire(90);
        //company.listEmpoeeys();
        company.getTopSalaryStaff(5);
        System.out.println("==============");
        company.getLowestSalaryStaff(5);
        //company.listEmpoeeys();
    }
}
